version: '2.1'
services:
    nextcloud-aio-portainer:
      image: portainer/portainer-ce
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - ./data/conf/portainer:/data
      restart: always
      networks:
        nextcoud-aio:
    
